import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Container } from '@mui/material';
import { useTranslation } from 'react-i18next';
import { useEffect } from 'react';

const Home: NextPage = () => {
  const { t , i18n } = useTranslation();
  useEffect(()=> {
    document.body.dir = i18n.dir();
  },[])
  
  return (
    <div className={styles.container}>
      <Head>
        <title>{t('home')}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container></Container>
      
    </div>
  )
}

export default Home
